services:
  - name: taskservice
    version: v1
    port: 8000

  - name: userservice
    version: v1
    port: 8000

  - name: tastore
    version: v1
    port: 8000

  - name: notifications
    version: v1
    port: 8000
